### ISSUE TITLE
Feature Request: Double click on item can run

### ISSUE THREAD

**Issue by doggy8088** [jaktestowac/vscode-playwright-helpers#1]
Because the Paste & run button is a bit small, it's a bit inconvenient:

![image](https://github.com/user-attachments/assets/61b22f8b-8c5d-404e-832e-dcf162a77b17)

Hope to support automatic invocation of Paste & run function by double-clicking with the mouse:

![image](https://github.com/user-attachments/assets/79ae75c7-0262-4efd-8b09-cc56fcdc2e54)

**Comment by Freudenberger** [comment]
Done in v1.0.4.
