### ISSUE TITLE
Running traces what were created form file placed in folder with spaces in name results with error

### ISSUE THREAD

**Issue by jaktestowac** [jaktestowac/vscode-playwright-helpers#11]
![obraz](https://github.com/user-attachments/assets/1a27be0f-0145-432e-9f61-eb5cdae6b699)
folder with tests containing space in name
Then name of trace will contain spaces
![obraz](https://github.com/user-attachments/assets/e0a7ff85-a37e-40f7-a404-576f99621cb4)
Then traces wil not be run with plugin and running it will finish with error

**Comment by Freudenberger** [comment]
Fixed in v1.2.10
