### ISSUE TITLE
[Feature request] Add trace options to Command Coposer

### ISSUE THREAD

**Issue by jaktestowac** [jaktestowac/vscode-playwright-helpers#16]
You can specify few options in command line with trace options:
`--trace <mode>	Force tracing mode, can be: on, off, on-first-retry, on-all-retries, retain-on-failure`

**Comment by Freudenberger** [comment]
All listed options are already implemented:
![obraz](https://github.com/user-attachments/assets/d4242754-91c6-4997-9fc7-3c207692b61b)

What version You are using?

**Comment by jaktestowac** [comment]
So is hard to discover some I was looking for trace not force 
Can we add search to this view so it is possible to filter, find desired options quickly?

**Comment by jaktestowac** [comment]
OK search is here - but tags can help in this situation:
![obraz](https://github.com/user-attachments/assets/09261b25-a0a3-420d-bb9e-44309791d968)

**Comment by jaktestowac** [comment]
That is a minor - so issue can be closed

**Comment by Freudenberger** [comment]
Added improvements in `v1.2.12` - now commands can be found by their names, eg `--trace` -> so search for `trace`.
