### ISSUE TITLE
List VSCode settings JSON on macOS (on Windows works fine)

### ISSUE THREAD

**Issue by jaktestowac** [jaktestowac/vscode-playwright-helpers#19]
Using this command (last on screenshot):
![obraz](https://github.com/user-attachments/assets/236d5649-20c8-4259-8973-bf2ae9474fc3)

opens User Settings JSON
And it is Windows compatible command
It is possible to make it work on macOS too?
For macOS the command looks like:
`open -a "Visual Studio Code" ~/Library/Application\ Support/Code/User/settings.json`

If not possible to make command depend on system then two separate commands dhould be available clearly saying what system it belong or command with option to specify system (default Windows).

**Comment by Freudenberger** [comment]
Done in `v1.2.15`

**Comment by jaktestowac** [comment]
Implementation not working due to changes in proposed command

**Comment by Freudenberger** [comment]
@jaktestowac can You please provide:
- actual result
- how actual command is working?
- expected command

**Comment by jaktestowac** [comment]
I placed command in issue description and that command is needed.
Current implementation missing backward slash.

**Comment by jaktestowac** [comment]
If slash is a problem the path after `~` can be surrounded with  `"`

**Comment by Freudenberger** [comment]
@jaktestowac please provide **screenshots** and/or **logs** from console. 

This will help me see the problem that You are talking about, because command is implemented the way You mentioned in first comment and I dont know how it works on Your MacOS. 

Please provide info about:
- actual result
- how actual command is working?
- expected command

**Comment by jaktestowac** [comment]
Ok:
1. Read carefully issue description https://github.com/jaktestowac/vscode-playwright-helpers/issues/19#issue-2735810286
2. Locate correct provided command (4th line from the end)
3. Replace broken implemented command in code with provided working command
Nothing more :D

**Comment by Freudenberger** [comment]
Without any additional info I will proceed with this fix:
```
'open -a "Visual Studio Code" "~/Library/Application Support/Code/User/settings.json"'
```

Also in future I would greatly appreciate it if, next time you raise or reopen an issue, you provide the minimal input I requested (**screenshots** and **logs**) and not only vague description.

This will help me begin investigating the issue and working on a possible fix more efficiently.

If You need help with how to report an issue or what should be provided - please dont hesitate to sak me - I would gladly help You :) 

Thank You for Your cooperation!

**Comment by Freudenberger** [comment]
Fix introduced in 1.2.16.

**Comment by jaktestowac** [comment]
It will not work: see my comment https://github.com/jaktestowac/vscode-playwright-helpers/issues/19#issuecomment-2551469960

**Comment by jaktestowac** [comment]
Also in future I would greatly appreciate it if, next time you use provided information in description and implement exact command or inform about modifications.
Adding modified one and closing issue do not lead to resolution. 

The command was provided in issue description. Bug was introduced. My answer was clear:
> Implementation not working due to changes in proposed command

So: command was proposed, implementation was buggy, task reopened to be fixed.
I can copy and paste over and over issue description but is not a point :D

Also what make communication hard is no answer to my comments but copying and pasting same phrase about screenshots etc. I'm expecting discussion form both sides here not bot comments.

**Comment by Freudenberger** [comment]
@jaktestowac I agree - thats why I prepared for You a brand new template to report new issues and/or features. 
This way You will have clear guidelines and steps to fill during reporting new issue.
This way It will be more readable and I will save us some time talking about issue without clear details :) 

```
So: command was proposed, implementation was buggy, task reopened to be fixed.
```
Thats great, because thats a part of a process! :D 
But with reopening an issue I expect You to provide detailed information about what was buggy, what was wrongly implemented and whats the expected outcome.

**Comment by Freudenberger** [comment]
Closing this issue because of lack clear informations and steps about the issue.
If issue still exists - please report new issue according to new guidelines and template :) 
Thank You!
