### ISSUE TITLE
GitHub Repo might add a link to VS Code marketplace

### ISSUE THREAD

**Issue by doggy8088** [jaktestowac/vscode-playwright-helpers#6]
You can put a [marketplace link](https://marketplace.visualstudio.com/items?itemName=jaktestowac-pl.playwright-helpers) to the repo. See screenshot below:

![image](https://github.com/user-attachments/assets/70440e6b-e836-4c5f-ace0-1ef5fe5e1449)

> The same for other 3 extensions.

Here is a sample:

![image](https://github.com/user-attachments/assets/238bca26-4ff3-418c-b1e5-186ebcf8fa7a)

**Comment by Freudenberger** [comment]
Good idea! 
Done - Ive added the link to marketplace.
I've also added links to other extension repositories.
